### ISSUE TITLE
disappear "glfxScanner.h" 

### ISSUE THREAD

**Issue by WindyPaper** [simul/glfx#1]
Excuse me.I want to know whether "glfxScanner.h" has been deleted?

**Comment by rvkennedy** [comment]
Yes, it's a generated file (created by compiling glfx.lpp) so it should not be stored in the repo. You need Flex and Bison to compile the lpp and ypp files into C++, please message me if you need help getting hold of these tools or setting them up.

**Comment by WindyPaper** [comment]
Thank you for your quick reply.Now I have a problem on Windows in "glfx_Win32_VC11.vcxproj".I can't import "SimulDLL_VC11.props" project.It seem has no these projects in simul/glfx.Is it necessary for compiling?I also generated VS2013 project by cmake,but it didn't work...Could you talk me how to compile a lib on Windows of VS project? Thank you.

**Comment by rvkennedy** [comment]
I've moved the .props files into the main directory and added them to the repository, this should fix the issue.

**Comment by WindyPaper** [comment]
Thanks for helping.Now I have compiled successfully!!

**Comment by WindyPaper** [comment]
Excuse me.Could you upload a GLSL FX file as sample?I cann't parse fx file which like glfx doc say.here is my fx file:

struct VSOutput
{
    vec2 TexCood0; 
    vec3 Normal0;
};

uniform mat4 g_View; 
uniform mat4 g_Proj; 
uniform mat4 g_Model; 

shader VS_Main(in vec3 Position, in vec2 TexCood, in vec3 Normal, out VSOutput VSout)  //here an error to occur
{  
    gl_Position = vec4(Position, 1.0) \* (g_Model \* g_View \* g_Proj);  

```
VSout.TexCood0 = TexCood;
VSout.Normal0 = Normal;
```

}

//-----------------------------------------------------------

uniform sampler2D Texture0; 

shader FS_Main(in VSOutput VsIn, out vec4 FragColor) 
{  
    FragColor = texture2D(Texture0, VsIn.TexCood0.st);
    //FragColor = vec4(0, 1, 0, 1);
} 

technique test_tech
{
    pass p0
    {
        vs(430) = VS_Main();
        fs(430) = FS_Main();
    }
}

error:fx(12) : glfx syntax error: "(" syntax error, unexpected '(', expecting IDENTIFIER in default state
